### ISSUE TITLE
Some PRs need to be rechecked, closed by ghost account that left

### ISSUE THREAD

**Issue by TwoSixtyThreeFiftyFour** [Anon-Planet/thgtoa#100]
Pr List:

- 94
- 93
- 78 but no clue what it is
- 60 IMHO We should have

**Comment by pterocles** [comment]
Rechecked how? It's not archived and I have no idea where to check for stale PR's of deleted accounts.

**Comment by pterocles** [comment]
I figured it out. All useful additions have been integrated now.

- #105 
- #107
- (abandoned) #60
