### ISSUE TITLE
Addition of IPFS mirror?

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#11]
Please consider the addition of an IPFS mirror using: https://pinata.cloud/

You can then just make a DNS redirect from like "ipfs.anonymousplanet-ng.org" to the domain provided by Pinata.cloud.

**Comment by Lefty-Insider** [comment]
NFTs are the digital equivalent of a banana duct-taped to a wall: something literally anyone can own at little or no cost, yet they now want you to pay for the idea of its ownership. This now a world where celebrities are coughing up more than half a million dollars for a jpeg of a cartoon ape, and it is clear that the sector has been overrun by greed

**Comment by NobodySpecial256** [comment]
Usually when people pay millions for such a half-assed piece of "art" they're actually using the transaction to launder money. Also, I fail to see how NTFs are in any way related to the addition of an IPFS mirror
