### ISSUE TITLE
(Urgent) Layout issue 

### ISSUE THREAD

**Issue by TwoSixtyThreeFiftyFour** [Anon-Planet/thgtoa#113]
See image from Tor Browser with Standard level

![image](https://user-images.githubusercontent.com/108928957/178527615-6565acbe-b680-414c-ae5e-33dee562aa3b.png)

Making PR

**Comment by dan-kir** [comment]
I can't tell from the screenshot what the problem is?

Did this need to be tagged as urgent?

**Comment by pterocles** [comment]
It's the same in Firefox. We could move it to the right, or link to it in the header and change the Twitter link to say "Mastadon"?
