### ISSUE TITLE
Find references , add to the acknowledgments and link the person.

### ISSUE THREAD

**Issue by TwoSixtyThreeFiftyFour** [Anon-Planet/thgtoa#144]
Please review:

- https://officercia.mirror.xyz/
- https://hackernoon.com/a-cia-agents-guide-to-steganography-fooling-the-kgb-and-protecting-your-crypto
- https://hackernoon.com/a-view-on-opsec-through-the-prism-of-time
- https://github.com/OffcierCia/Crypto-OpSec-SelfGuard-RoadMap

This is from a person who was kind enough to retweet us, like us, link us and recommend us. 

@officer_cia on twitter

Urgent priority, due tomorrow. Thanks to this person we might recover a lot of our lost community on twitter.

**Comment by pterocles** [comment]
It's not HIGH PRIORITY, it's just common courtesy.

**Comment by NobodySpecial256** [comment]
Normally I'd be opposed to adding someone to the guide based on their support for us alone, but this looks like it's actually a great resource that I would want to add to the guide anyway. I added a couple of their articles in relevant sections of the guide, as well as adding their blog to the links page
