### ISSUE TITLE
Contrary to #147, #148 and #154, Remove the whole section.

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#154]
Contrary to #147 ,#148, and #154

I propose the removal of the whole "When using BTC: bonus step for improving your privacy using obfuscation:" section.

My arguments:

- Only Monero and ZCash can provide actual anonymity
- This is only obfuscation and can be broken
- This guide is about anonymity. Should not be proposing any of those silly mixing wallets.

**Comment by dan-kir** [comment]
There seems to be an attitude that you're either completely, 100% bulletproof anonymous or you're not. We need to continue to provide options. Threat models and situations vary.

I agree that Monero (XMR) should be the preference wherever possible. But XMR is not accepted everywhere and sometimes Bitcoin is the only option.

- Until recently you couldn't pay for Mullvad VPN with XMR. You could with mixed BTC.
- You can't donate to Signal with XMR. You can with mixed BTC.
- Appears 1984 no longer list XMR as a payment option?

You get the point. Sometimes it's best effort and there are many cases where XMR is not accepted for whatever reason while BTC is.

If you know how to trace and attribute a Whirlpool BTC UTXO then please share your methods.

We even accept Bitcoin for THGTOA however you're suggesting we remove any recommendations on how to do so privately.

**Comment by pterocles** [comment]
Well, looks like it's a conflict of interest then? If we can't show how to donate to either us or another service anonymously using BTC through such methods, then we've failed.

**Comment by dan-kir** [comment]
> Just buy Monero directly (kraken) transfer to your wallet
Isn't Kraken a KYC exchange? You need to provide proof of identity for an account? As soon as you log in, you're no longer anonymous.

The process of swapping back and forth is advanced. Likely too advanced for many users.

> We have to provide options that provide anonymity. And we have enough with Monero and Zcash.

So how to I pay for goods/services with some level of anonymity online when the vendor only accepts BTC?
