### ISSUE TITLE
Why is the makefile flow making HTML files using pandoc instead of using Bundle?

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#155]
Why are we making HTML files ourselves?

That's unnecessary, test it locally with Bundle ("Bundle exec jekyll serve")  and it will generate the HTML files and everything from the md files exactly using the same versions than GitHub.

And if you want a "mirror", then you issue "bundle exec jekyll build" which will build the site locally and can then be uploaded to mirrors.

It's safer, better, more efficient to do it the bundle way. 

See: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll

This way uses the same versions as GitHub. This is definitely the best way to make the HTML part

**Comment by pterocles** [comment]
You don't need to mansplain it. Just PR it, show us it works and if it does, it will be merged. I have never done it that way, because I didn't know. You've explained it many times now.

**Comment by pterocles** [comment]
Private repos allow github-pages (with GitHub Enterprise Cloud). So it's not feasible on regular github. We could just use Surge to have previews.
