### ISSUE TITLE
i cant click on "windows 10/11 vm" in "contents:" and some addons are unnecesarry

### ISSUE THREAD

**Issue by takemeonduduuuu** [Anon-Planet/thgtoa#165]
multiple addons are unnecessary, see the arkenfox wiki: https://github.com/arkenfox/user.js/wiki/4.1-Extensions

**Comment by pterocles** [comment]
> We do need to update the addons/extensions. Thank you for contributing @takemeonduduuuu

Also including in my PR linked above.
