### ISSUE TITLE
Consider adding macos (ventura) privacy guide by Michael Bazzell

### ISSUE THREAD

**Issue by lepras** [Anon-Planet/thgtoa#281]
Seeing the new sec guide added for macos in the latest release, this guide comes to mind.

https://inteltechniques.com/ventura.html

Though its for a specific macos version, it applies to all.

**Comment by sharp-tailed** [comment]
Interesting addition to the guide. I don’t use macOS but if someone with it were willing to contribute this into the section regarding Mac I would be happy to include it. Thanks for taking time to share this information.   On Sat, Apr 1, 2023 at 10:05 AM, Lepras ***@***.***> wrote:  
Seeing the new sec guide added for macos in the latest release, this guide comes to mind.
https://inteltechniques.com/ventura.html
Though its for a specific macos version, it applies to all.

**Comment by DeckhardRick** [comment]
Michael Bazzel is a greedy for-profit person, while some of his information might be useful, be careful about his copyright stance and DMCA requests. It's a core principle of this project to remain free and available to all. As well as it's a core principle that it should never be used commercially as the Licensing chosen by the founder.

**Instead, there is https://github.com/drduh/macOS-Security-and-Privacy-Guide already referenced in the guide, providing the same information, open-source, free and maintained. I recommend collaboration with that project instead.**

Be careful of DMCAs as he is known for sending them just for quoting passages of his guides and books.

**Comment by sharp-tailed** [comment]
Closing because M. Bazzel is not a cool person. I will leave refs to his past work, but I won't put any of his work in the guide because I don't want to deal with the legal issues that may arise.
