### ISSUE TITLE
consider dividing the guide.md into modules and files

### ISSUE THREAD

**Issue by lepras** [Anon-Planet/thgtoa#282]
Its difficult to contribute and make sense of the guide if its just one file. 

I think we should structure it into folders and files.

**Comment by sharp-tailed** [comment]
This is a HUGE ask. I'll consider it, but it's a multi-person job. It could be a website with static pages, sort of like a flip book. But that would take a long time. I'd have something like `issue282-split-doc` as a draft for like 6 months if it were just me. It's not a bad idea, just not reachable right now.

**Comment by DeckhardRick** [comment]
This is against the wishes of the founder of this guide ... it's intentionally meant as remaining in "book" style for accessibility over ergonomics ...

**Comment by sharp-tailed** [comment]
No matter what format the website were to be, I would still be providing the PDF and other formats. The build is now fairly easy, I can do both.
