### ISSUE TITLE
PDF is all wrong, superscript is not working and all your wikilesss/archive.org/... are broken

### ISSUE THREAD

**Issue by Snorkeldink** [Anon-Planet/thgtoa#332]
### Affected section of the guide

The PDF

### Short description

See title ... Superscript links are broken in the PDF

### Research

I'm not knowledgeable enough on that specific conversion from markdown/kramdown to PDF to really help and suggest meaningful changes. Apologies.

### Required checks

- [X] This is not an opinion. It is fact. It is backed by [my own] research.
- [X] I agree to the [PSA Code of Conduct](https://anonymousplanet.org/export/CODE_OF_CONDUCT.html).

**Comment by Snorkeldink** [comment]
Ignore, it's working but they're not highlighted as links. Sorry. Closing.

**Comment by nopeitsnothing** [comment]
The PDF has known issues such as superscript errors, images resizing, etc. I'm working on the new site design, available in https://github.com/Anon-Planet/thgtoa/tree/mkdocs-rebuild. Thanks for your time.
