### ISSUE TITLE
Replace text "This guide is a work in progress. It will probably never be “finished”."

### ISSUE THREAD

**Issue by Snorkeldink** [Anon-Planet/thgtoa#334]
### Affected section of the guide

The guide itself, first line after the Ukraine part

### Short description

Replace text `This guide is a work in progress. It will probably never be “finished”.` with `This guide will never be final and will always remain a work in progress.`

There is no "probably" as it's just not possible. 

### Research

None

### Required checks

- [X] This is not an opinion. It is fact. It is backed by [my own] research.
- [X] I agree to the [PSA Code of Conduct](https://anonymousplanet.org/export/CODE_OF_CONDUCT.html).

**Comment by nopeitsnothing** [comment]
It will never be finished. I will remove this in the new build as well.
