### ISSUE TITLE
Link in README.md is broken

### ISSUE THREAD

**Issue by EpicSegfault** [Anon-Planet/thgtoa#350]
The link [IMPORTANT RECOMMENDATION FOR UKRAINIANS. ВАЖЛИВА РЕКОМЕНДАЦІЯ ДЛЯ УКРАЇНЦІВ](https://github.com/Anon-Planet/thgtoa/blob/main/briar.html) is broken.  The link should point to https://github.com/Anon-Planet/thgtoa/blob/main/briar.md.

**Comment by NobodySpecial256** [comment]
The link is meant to be viewed from https://anonymousplanet.org, not through the git repo directly. The actual link is to https://anonymousplanet.org/briar.html, which seems to be working.
