### ISSUE TITLE
Request/Proposal: create an organization to have collaborators and more features

### ISSUE THREAD

**Issue by Batcherdink** [Anon-Planet/thgtoa#45]
I think it would be wise to create an organization for this project rather than a single repository on one account.

Eventually with time you might even designate a co-maintainer in case something happens to you.

What do you think?

**Comment by 1z5q** [comment]
Agree with @Batcherdink!

**Comment by thanharrison** [comment]
Been saying this a while but I also would turn the offer down because of the malicious attention it would attract to anybody that did.
