### ISSUE TITLE
Qubes OS , anti-evil-maid section addition 

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#67]
We need to add information about their anti-evil-maid system (<https://www.qubes-os.org/doc/anti-evil-maid/>) in our <https://anonymousplanet-ng.org/guide.html#hardening-qubes-os> section.

But this works only on an Intel CPU.

Babba and myself are AMD.

We need to find someone to write not a "tutorial" but more like an experience report, issues you might encounter, things should be careful for etc etc in addition to linking to their tutorial (if their is one). If there is none, we have to make one.

**Comment by thanharrison** [comment]
I don't have the hardware right now for Qubes, but I'm on an Intel laptop.

**Comment by dan-kir** [comment]
I have the required spare hardware and will fold this work in with my confirmation of the Qubes OS route #68

**Comment by dan-kir** [comment]
Anti Evil Maid addition here -> https://github.com/Anon-Planet/thgtoa/pull/109
