### ISSUE TITLE
Flow check of the routes

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#68]
Please assign this issue to Dan-Kir

The goal is to check the flow of the routes to see if well ... the flow is correct and you don't get stuck at some point or sent to a wrong section or something.

**Comment by dan-kir** [comment]
"Flow or the routes" meaning the general flow of the document? I'm not sure what this is.

**Comment by dan-kir** [comment]
Got it.

I think this issue should probably be broken up into a few smaller issues. Likely a separate issue to check and verify each route individually.

I will start with checking and verifying the Qubes OS route for Qubes release 4.1.1-rc1

**Comment by dan-kir** [comment]
The flow for the Qubes route is fine.

Minor updates here -> https://github.com/Anon-Planet/thgtoa/pull/109
