### ISSUE TITLE
Low skill user sent to advanced user content?

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#69]
Please assign this issue to Dan-kir

It has been reported to me that sometimes you have low skilled user (in the low skilled routes) sent suddenly to an advanced user section. Which they won't understand.

We need to identify those. I asked Dan-kir to do this.

**Comment by dan-kir** [comment]
Unless someone provides an example of this occurring I don't have much to work with. Suggest this issue is closed.
