### ISSUE TITLE
Update of contributing guidelines proposal about metadata of binaries

### ISSUE THREAD

**Issue by ghost** [Anon-Planet/thgtoa#81]
Contributing guidelines should IMHO also make it clear that any upload of new binaries such as pictures should be cleaned from all metadata using exiftool. 

Now personally, for ease of use, I recommend <https://exifcleaner.com/> (available on all platforms) which will do the same (it's just a GUI front-end of exiftool) but you can just drag and drop files in the interface (multiple if you want).

Works on all file formats and not only on pictures.

Contrary to the name "exif" which concerns only pictures, it works for all metadata on all types of files.

**Comment by 1z5q** [comment]
Didn't know it cleans PDF ans MP4 formats too. Thanks for the clarification.

**Comment by pterocles** [comment]
Closing as complete because we will not be allowing any files that are not ran through a metadata scrubber like ExifCleaner prior to upload. This is just general practice.
