### ISSUE TITLE
Add Skiff (discussion)

### ISSUE THREAD

**Issue by pterocles** [Anon-Planet/thgtoa#96]
# Skiff

## Threat model
Skiff, unlike most other collaboration workstations, provides private and secure collaboration. Skiff’s threat model is an adversary that, according to them, "may access any data sent over a network to or from a client (even data sent over encrypted network connections). It also assumes that data stored with a cloud provider cannot be assumed to be confidential."

## Tor signup
This is possible but you may encounter things such as regular Captcha's and other annoyances, but that wouldn't make it unusable. They don't have a Tor V3 onion service.

[Skiff](https://www.fastcompany.com/90696585/skiff-ipfs-storage-private-document-editor) is an ecosystem, much like Google's products. It has both a free and priced ("pro") tier, from which you can benefit from its use of extended version history for files, more options for collaboration, etc. But payment isn't required and isn't necessary for base usage. They offer an e-mail extension (in terms of its reach not an actual extension for your browser; i.e., it offers its own collaboration e-mail that functions like a server e-mail); pages for creating wikis and other documents; and a Google Drive-esque product that, overall, has the ability to perform much like Google Docs, but with the addition of data protection and privacy enhancing techniques. The product is [open-source](https://github.com/skiff-org), on top of this. I don't know whether this is the full source for everything yet) 

Skiff is a document editor at its roots. Similar to Google Docs, it allows you to "write, edit and collaborate in real time with colleagues with privacy baked in." Skiff doesn’t have the ability to access anyone’s data and most, if not all, metadata. "Only users, and those who are invited to collaborate, do."

> It’s an idea that has already attracted the attention of investors. Skiff’s co-founders Andrew Milich (CEO) and Jason Ginsberg (CTO) announced today that the startup has raised $3.7 million in seed funding[^2] from venture firm Sequoia Capital, just over a year since Skiff was founded in March 2020. Alphabet chairman John Hennessy, former Yahoo chief executive Jerry Yang and Eventbrite co-founders Julia and Kevin Hartz also participated in the round.

> Skiff isn’t that much different from WhatsApp or Signal, which are also end-to-end encrypted, underneath its document editor. “Instead of using it to send messages to a bunch of people, we’re using it to send little pieces of documents and then piecing those together into a collaborative workspace[.]”

> The co-founders acknowledged that putting your sensitive documents in the cloud requires users to put a lot of trust into the startup, particularly one that hasn’t been around for long. That’s why Skiff [published a whitepaper](https://skiff-org.github.io/whitepaper/Skiff_Whitepaper_2022.pdf) with technical details of how its technology works, and has [begun to open source](https://www.skiff.org/updates/skiff-is-open-sourcing) parts of its code, allowing anyone to see [how the platform works](https://github.com/skiff-org/skiff-mail). Milich said Skiff has also gone through at least one comprehensive security audit, and the company counts advisors from the Signal Foundation to Trail of Bits.

## Products (w/ E2E encryption)

- [Mail](https://www.skiff.com/mail)
- [Pages](https://www.skiff.com/pages)
- [Drive](https://social.techcrunch.com/2021/05/26/skiff-encrypted-collaboration-seed/)

## Availability

Skiff is currently available through:

- Any browser, 
- [iOS app](https://apps.apple.com/us/app/skiff/id1599795319),
- [Android app](https://play.google.com/store/apps/details?id=com.skiffmobileapp&hl=en_US&gl=US),
- [Mac desktop app](https://github.com/skiff-org/skiff-org.github.io/tree/main/macos)

## Document types supported 
> You can upload .docx, .pdf, or .md files, or import documents directly from your [Google Docs](https://www.skiff.com/blog/import-google-docs) using our instant migration tool. You can also embed files of any type into your Skiff pages for collaborators to download. Read more about Skiff’s file embeds here.

## "/" Commands
> “/” commands allow you to access all the cool features Skiff has to offer without lifting your hands from your keyboard. By hitting the “/” key on your keyboard, a dropdown list of commands will pop up for your selection. Select commands such as “Code” to insert a code block, “Equation” to insert a mathematical equation, and many more awesome features.

## Document encryption
> Every document is associated with a short-term symmetric session_key as well as an asymmetric “hierarchical” key-pair. The session_key is used to encrypt all document contents and metadata that are stored on the server. In order to support real-time collaboration and simple sharing mechanisms, all collaborators - say Alice and Bob - have access to the same session_key. However, because Alice and Bob have different asymmetric key pairs, they each have unique encrypted copies of the same session key (encrypted with public_key_Alice and public_key_Bob, respectively). Using this symmetric session_key, we can outline processes for creating, editing, and sharing documents ... a document’s hierarchical key can be used for constructing a scalable filesystem out of many thousands of documents.

## Document history
> You can always use the Version History feature to view and restore previous versions of your pages. Free tier users can look back up to 24 hours

## Account recovery
> When users forget their password, it’s convenient for them to have a way to recover their account and reset their password. This is achieved using a recovery key (a symmetric key similar to the password_derived_secret). A user can enable account recovery in their settings, which generates a recovery key. The recovery key is used to encrypt the user’s private data (i.e. private keys); this encrypted user data is stored by Skiff but inaccessible.

**Comment by dan-kir** [comment]
How and why should this be included into the guide?

Does Skiff offer any additional anonymity?

We decided not to include GrapheneOS as it was not an anonymity tool but a privacy and security one. (Also because some people believe you can't operate anonymously from a mobile device).

**Comment by pterocles** [comment]
No interest for this on Mac so I'm closing this.

**Comment by pterocles** [comment]
Nate at The New Oil has brought this up now as well, considering Skiff for their Encrypted Messaging section:

**[Andrew Milich, CEO] has replied to some of these concerns via Reddit.**

1. Q: "Please note that we do not respond to or honor DNT signals or similar mechanisms transmitted by web browsers."
> Reply: "we do not do any tracking or analytics already, so there would be nothing we could do with a "do not track" signal."

2. Q: "We....may receive billing address or other non-sensitive information associated with your payment card from our third-party processors."
> Reply: We do not collect or store payment processing information. However, we are periodically required to assist in payment questions via our support channels.

3. Q: "You can use your mobile device settings to limit use of the identifier(s) associated with your device for interest-based advertising purposes and for location tracking." (Does this mean limiting tracking is only available via the mobile apps?)
> Reply: There is no tracking on the web apps or mobile apps. This section of the policy refers to device/operating system preferences.

4. Q: "Interactive Features." Does this apply only to things that are shared outside of Skiff?
> This applies only to communications with the Skiff team (this was explained to me in a DM so I can't post the source link.)

5. Q: "What cryptography do they use? Is it self-rolled?"
> Reply: "On cryptography, our whitepaper shares information on the general cryptography choices - login, authentication, keypairs, etc. It's quite similar to password managers or encrypted communication apps. In the actual product (code here https://github.com/skiff-org/skiff-mail), we use the library TweetNaCl (https://github.com/dchest/tweetnacl-js) which is designed to be fast, trustworthy, and performant"

6. Q: "Do they allow users to access and share public keys so non-Skiff users can initiate secure conversations (such as PGP)?"
> Reply: "if you visit the settings page, you will see a "verification phrase" that can be shared with other users to mark them as verified (like the Signal feature). For external communications, I recommend using a Skiff Page or document and sharing via an end-to-end encrypted link."

Source: https://www.reddit.com/r/thenewoil/comments/w3wqbd/comment/igz1m83/?context=3

**Comment by pterocles** [comment]
I thought this looked like a good addition. I vetted them and their services are okay for encryption and privacy. More for regular threat models; people looking for privacy when collaborating, you'll find that it is E2E encrypted and very private. I guess I'll close this. I don't know.

**Comment by pterocles** [comment]
> I think we should at least mention them somewhere ... but your issue, your call

Well, admin doesn't see it that way.
